# Generated by Django 4.2.2 on 2023-06-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentdetails",
            name="roll_no",
        ),
        migrations.AlterField(
            model_name="studentdetails",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
