# Generated by Django 4.2.2 on 2023-06-30 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userApi", "0002_remove_studentdetails_roll_no_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentdetails",
            old_name="id",
            new_name="rollno",
        ),
    ]
